Integrate change 553387 from zimbra to JUDASPRIEST
-------------
Bug: 100414 - Script Error: "t.getFocusMember is not a function" while click on Attachment filter from Search window
When pushing/popping a menu's tab group, use the
composite tab group instead of calling getTabGroupMember(),
which will return the menu if no items have been added yet.
Expand the check in the keyboard mgr to make sure the
argument passed to push/pop is a DwtTabGroup.

https://bugzilla.zimbra.com/show_bug.cgi?id=100414

Copied from Perforce
 Change: 553388